apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.component_id}}
  labels:
    app: ${{values.component_id}}
    component: web
spec:
  selector:
    matchLabels:
      app: ${{values.component_id}}
      component: web
  template:
    metadata:
      labels:
        app: ${{values.component_id}}
        component: web
    spec:
      containers:
      - name: ${{values.component_id}}
        image: diegoluisi/${{values.component_id}}:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 512m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 256Mi